### PR TITLE
adds IVMeterControl

### PR DESCRIPTION
**Pull request by Eugene-Y**

### CODE REVIEW

**Comment by olilarkin** [comment]
this is great, will look at how best to merge soon. I want to reduce the amount of code necessary for controls like this, will see how much can be brought into the library

**Comment by Eugene-Y** [comment]
As usual there are several  helper functions for IRECTs and basic text measurement,  and  this time there is some WDL_String processing stuff like removing trailing zeroes.

**Comment by Eugene-Y** [comment]
the only thing I forgot is to cleanup the colors. I wanted to set these colors in the constructor to avoid using static members.

**Comment by olilarkin** [comment]
you can keep pushing to the PR if you forgot something

**Comment by olilarkin** [comment]
I have merged this work into the iplugquake-vcontrols branch. Closing this pull request.

https://github.com/olilarkin/wdl-ol/tree/iplugquake-vcontrols

**Pull request closed without merging**
