### PR TITLE
Update Doxyfile for neater output, Add documentation for IPlugBase::ProcessDoubleReplacing

### PR DESCRIPTION
**Pull request by QrchackOfficial**
Various other tweaks:

Change \return to @return for IControl::GetTooltip()
Add documentation for IControl: ParamIdx(), GetValue(), GrayOut(), IsGrayed()
Add documentation group for struct IControl::AuxParam
Add documentation for GetAuxParam(), AuxParamIdx(), AddAuxParam(), SetAuxParamValueFromPlug()
Add documentation for IControl::mParamIdx
Add documentation for struct IBitmap::N
Add documentation for IPlugBase::ProcessDoubleReplacing() with example code

### CODE REVIEW

**Comment by QrchackOfficial** [comment]
Added in d097eb9d653ac1f3eca12614a6fb9f8e9514001c:

version 2 -> 2.0
Remove Doxyfile comment blocks
Remove Perl module output support
Remove redundant default values
Add Documentation/src to begin static pages support
Remove explicit file extension list (it was default anyway)
Add "Definition at line X of file Z.h"
Remove side panel tree view (GENERATE_TREEVIEW = NO)
Remove class diagrams (CLASS_DIAGRAMS = NO)

**Comment by QrchackOfficial** [comment]
How's that for some useful documentation?

image

**Comment by olilarkin** [comment]
great, good work!

**Comment by olilarkin** [comment]
great, if we can link in all the Readme.md files in various directories, that would be brill

**Pull request merged**
